### ISSUE TITLE
As a Wizards' Guild Member, I want to be able to see a description of each element on the element page so that I can know more about each element

### ISSUE THREAD

**Issue by Samgotdam** [Samgotdam/Elemental2#7]
As a Guild Member, I want to be able to see a description of each element on the element page so that I can know more about each element

**Comment by oppenheip** [comment]
This is not a requirement. The Wizards Guid didn't ask for a description of each element. An important aspect of Systems Analysis is requirements analysis, i.e. understanding what the user wants. 

Are you making up requirements in order to have enough stories? You will have more stories if you make each story more fine-tuned. Note this statement in the exercise: The User Stories should be fine-grained; create one User Story for each change you need to make to a given page. 

You need a new link on index, a new page for selling, a new hat page, a new wand page, a new link on each element page. It shouldn't be hard to get enough user stories.
